export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REQUEST_PASSWORD_RESET_LINK = 'REQUEST_PASSWORD_RESET_LINK';
export const RESET_PASSWORD = 'RESET_PASSWORD';
