export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const REQUEST_USER_DETAILS = 'REQUEST_USER_DETAILS';
export const REQUEST_USER_DETAILS_SUCCESS = 'REQUEST_USER_DETAILS_SUCCESS';
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';
